config/routes.rb
Rails.application.routes.draw do
  root to: 'links#index'

  resources :links do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  match('/links/:id/upvote', {:via => [:patch, :put], :to => 'upvotes#update'})

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, polymorphic: true
  has_many :comments, as: :post
  validates :description, presence: true

  def find_parent
    next_level = self.post
    until next_level.class.to_s == "Link"
      next_level = next_level.post
    end
    next_level
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :comments, as: :post
  validates :name, presence: true
  validates :url, presence: true
  validates :description, presence: true

  def upvote
    self.update(votes: self.votes + 1)
  end

  def self.sort_by_score
    self.all.sort_by{|link| link.votes / (Time.now - link.created_at)}.reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    if params[:comment_id] == nil
      @post = Link.find(params[:link_id])
    else
      @post = Comment.find(params[:comment_id])
    end
    @comment = @post.comments.new
  end

  def create
    if params[:comment_id] == nil
      @post = Link.find(params[:link_id])
    else
      @post = Comment.find(params[:comment_id])
    end
    @comment = @post.comments.new(comment_params)
    @link = @comment.find_parent
    if @comment.save
      redirect_to link_path(@link), notice: "New comment submitted! Congrats!"
    else
      render 'new'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @link = @comment.find_parent
    @comment.destroy
    redirect_to link_path(@link), notice: "New comment destroyed! Way to go!"
  end

  def edit
    @comment = Comment.find(params[:id])
    render 'edit'
  end

  def update
    @comment = Comment.find(params[:id])
    @link = @comment.find_parent
    if @comment.update(comment_params)
      redirect_to link_path(@link), notice: "Comment updated! Congrats!"
    else
      render 'edit'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:description)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to root_url, notice: "New Link submitted! Congrats!"
    else
      render 'new'
    end
  end

  def show
    @link = Link.find(params[:id])
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update(link_params)
      redirect_to link_path(@link), notice: "Link updated! Congrats!"
    else
      render 'edit'
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to root_url, notice: "Link removed."
  end

  private
  def link_params
    params.require(:link).permit(:name, :url, :description)
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def update
    @link = Link.find(params[:id])
    @link.upvote
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_comment.html.erb
<ul>
  <% post.comments.each do |comment| %>
    <li><%= comment.description %>
      <%= link_to "(remove)", link_comment_path(@link, comment), method: "delete" %>
      <%= link_to "(edit)", edit_link_comment_path(@link, comment) %>
      <%= link_to "(comment)", "/comments/#{comment.id}/comments/new" %>
      <%= render 'comments/comment', :post => comment %>
    </li>
  <% end %>
</ul>

app/views/comments/_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

<%= form_for [@post, @comment] do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <%= f.submit(class: "btn btn-primary") %>
<% end %>

app/views/comments/edit.html.erb
<h3>Edit comment</h3>

<%= render 'form' %>

app/views/comments/new.html.erb
<h3>Submit a new comment</h3>

<%= render 'form' %>

app/views/comments/show.html.erb
<h3><%= @link.name %></h3>
<h5><%= @link.url %></h5>
<hr>
<p><%= @link.description %></p>

<%= link_to "Edit", edit_link_path(@link), class: 'btn btn-info' %>
<%= link_to "Delete", link_path(@link), method: "delete", class: 'btn btn-danger' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Hacker News</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Post a link", new_link_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackernews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= render '/layouts/navbar' %>
  <%= flash[:notice] %>
  <%= flash[:alert] %>
  <%= yield %>
</div>
</body>
</html>

app/views/links/_form.html.erb
<%= render('layouts/errors', :object => @link) %>

<%= form_for @link do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <%= f.submit(class: "btn btn-primary") %>
<% end %>

app/views/links/index.html.erb
<ul>

  <% @links.sort_by_score.each do |link| %>

    <li>
      <%= link_to "Upvote", "/links/#{link.id}/upvote", method: 'patch'%>
      <p> Upvotes: <%= link.votes %> </p>
      <p> <%= link_to link.name, link_path(link) %> </p>
      <p> <%= link.url %> </p>
    </li>
  <% end %>

</ul>
<hr>
<%= link_to "Submit Link", new_link_path, class: "btn btn-success" %>

app/views/links/new.html.erb
<h3>Submit a new link</h3>

<%= render 'form' %>

app/views/links/show.html.erb
<h3><%= @link.name %></h3>
<h5><%= @link.url %></h5>
<hr>
<p><%= @link.description %></p>

<hr>
<% if @link.comments.length > 0 %>
<h5>Comments</h5>
<ul>
  <% @link.comments.each do |comment| %>
    <li><%= comment.description %>
      <%= link_to "(remove)", link_comment_path(@link, comment), method: "delete" %>
      <%= link_to "(edit)", edit_link_comment_path(@link, comment) %>
      <%= link_to "(comment)", "/comments/#{comment.id}/comments/new" %>
      <%= render 'comments/comment', :post => comment %>
    </li>
  <% end %>
  </ul>
<% end %>
<br>
<br>
<%= link_to "Comment", new_link_comment_path(@link), class: 'btn btn-success' %>
<%= link_to "Edit", edit_link_path(@link), class: 'btn btn-info' %>
<%= link_to "Delete", link_path(@link), method: "delete", class: 'btn btn-danger' %>